### ISSUE TITLE
Call a Remote Function Module (RFC): Test the Connection to the Remote System

### ISSUE THREAD

**Issue by flopezmm** [sap-tutorials/abap-core-development#18]
Tutorials: https://developers.sap.com/tutorials/abap-environment-test-rfc.html
--------------------------
Step 4 in this tutorial does not use ' ' for the values to create by communication arrangement. It might be misleading.

In addition, this is the first mission in the tutorial, so it makes the assumption the developer already knows how to setup the communication to an on-premise system. 

The following tutorial [here](https://developers.sap.com/tutorials/abap-env-rfc.html#b67991e6-c8af-427f-8e0f-7c42807a236d) is much better explained and runs without issues. It could be referenced to this one as prerequisite.

**Comment by julieplummer20** [comment]
Hi

**Comment by julieplummer20** [comment]
Hi,
This is NOT the first mission in the tutorial. The prerequisites include the following:
"- **IMPORTANT**: This tutorial is part of the mission [Connect Your On-Premise System with SAP BTP, ABAP Environment](mission.abap-env-connect-onpremise). **Please work through the previous tutorials in the mission first; otherwise this tutorial may not work"**
That is, it references the mission you cited.
I corrected the typo in step 4, thanks.
Best wishes,
Julie Plummer.
