### ISSUE TITLE
Connect SAP Business Application Studio and SAP S/4HANA Cloud System

### ISSUE THREAD

**Issue by mmarkvillanueva** [sap-tutorials/abap-core-development#1840]
Tutorials: https://developers.sap.com/tutorials/abap-custom-ui-bas-connect-s4hc.html
--------------------------

Receiving error in Step #4 when configuring communication system in S4HC. Getting "The uploaded certificate is invalid" when uploading the signing certificate generated from BTP Destination.

![image](https://github.com/sap-tutorials/abap-core-development/assets/43941530/bd882770-ad0f-4160-b45a-2059b9fff681)

**Comment by Liebherr** [comment]
Hello @mmarkvillanueva,
please excuse the late reply, but tutorial authors are mostly not responsible for the shown feature and do not provide support. As the tutorial states "in the Destinations section, select Download Trust" I assume by "uploading the signing certificate generated from BTP Destination" you uploaded some other certificate than the intended?
In general, if you face such issues, which have a technical flavour and seem not to be caused by shown obsolete UI or processes, please open a ticket to the component of the UI you are facing the issue at. You find it under the user icon > "About", in this case it's BC-SRV-APS-COM.
Thanks for your understanding.
Regards
Ulrike
